# version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: chiefbuilder/web

    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - static_volume:/home/app/staticfiles
    expose:
      - "8000"
    env_file:
      - ./env_files/app.env
    depends_on:
      - db

  nginx:
    build:
      context: nginx/
    image: chiefbuilder/ingress
    volumes:
      - static_volume:/home/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./env_files/pg-db.env
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - ./env_files/pg-admin.env
    environment:
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorisedusers"
    ports:
      - "5050:80"
    restart: always

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

volumes:
  postgres_data_prod:
  static_volume:
